### PR TITLE
replaces kmc-gcc-wrapper with native kmc gcc port

### PR DESCRIPTION
**Pull request by gumorr**
what it says on the tin, replaces the kmc gcc wrapper with a native kmc gcc/binutils port from https://github.com/decompals/mips-gcc-2.7.2 and https://github.com/decompals/mips-binutils-2.6

also includes some other minor changes in the makefile so itll play nice with other linux distros aside from debian.

### CODE REVIEW

**Comment by freem** [comment]
Thanks for the contribution; however, I couldn't exactly get it to work.

I pulled the repo, switched to the `gcc_kmc` branch, pulled again to make sure I had the right files, ran `make` in the tools directory to generate the toolset, but ran into an issue when attempting to build the project:

```freem@portatank:/mnt/c/freemdev/akiclub/vpw2_gumorr$ make
gcc -fsyntax-only -fno-builtin -fsigned-char -std=gnu90 -m32 -Wall -Wextra -Wno-format-security -Wno-unknown-pragmas -Wunused-function -Wno-unused-parameter -Wno-unused-variable -Wno-missing-braces -Wno-int-conversion -I include src/textmain.c
COMPILER_PATH=tools/gcc_kmc/linux/2.7.2 python3 tools/asm-processor/build.py tools/gcc_kmc/linux/2.7.2/gcc -- mips64-elf-as -EB -mtune=vr4300 -mabi=32 -march=vr4300 -I include -- -c -c -G0 -mips3 -mgp32 -mfp32 -O2 -I include -nostdinc -o build/src/textmain.o src/textmain.c
cpp: include/common.h: Value too large for defined data type
cpp: include/ultra64.h: Value too large for defined data type
Failed to compile file src/textmain.c. Command line:

tools/gcc_kmc/linux/2.7.2/gcc -c -c -G0 -mips3 -mgp32 -mfp32 -O2 -I include -nostdinc -I /mnt/c/freemdev/akiclub/vpw2_gumorr/src -o build/src/textmain.o /tmp/preprocessedwsf2dm6a.c

make: *** [Makefile:192: build/src/textmain.o] Error 55
```

Unfortunately, this error message doesn't appear to be of any help. The only thing I can think of is that it's choking on something in `ultratypes.h`, but I have no leads on this.

edit: this is on WSL2 Debian; `uname --a` output:
`Linux 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux`

**Comment by gumorr** [comment]
did some research, apparently this is a wsl issue https://github.com/microsoft/WSL/issues/7175
gonna change this to compile gcc and binutils from source with the necessary fixes

**Comment by gumorr** [comment]
finally got around to this again, ended up just making a fork of the two github repos im pulling the gcc ports from and added the file offset bit fix to the build workflows for them (couldnt get them to build locally). im not on windows so i dont really have a decent way of testing if this has fixed whatever was going on with wsl, but it does still seem to compile the game fine for me.

**Comment by freem** [comment]
if I comment out the (extra?) `CROSS = mips64-elf-` on line 72 of the Makefile, everything seems to be working as intended.

**Pull request merged**
